### ISSUE TITLE
NoMethodError (undefined method `advance' for #<Date 2010-10-02>):

### ISSUE THREAD

**Issue by BrianTheCoder** [jeremyevans/home_run#17]
http://gist.github.com/607509

**Comment by jeremyevans** [comment]
advance isn't a core Date method, it's added by active_support.  This is probably a dup of #12.  This is either happening because you are loading active_support before home_run or you are not loading active_support, with the first being more likely.

You need to make sure that you are using `home_run --install` to install to site_packages or `home_run command` to run the command.
