### ISSUE TITLE
Subtraction failing using ActiveSupport and DateTimes unsing REE 1.8.7 and Ruby 1.9

### ISSUE THREAD

**Issue by xn** [jeremyevans/home_run#20]
See gist please.
https://gist.github.com/714891

**Comment by jeremyevans** [comment]
This is failing because active_support assumes that DateTime inherits the - method from Date.  This is true in the standard library, but in home_run, DateTime implements it's own - method.  Since active_support only overrides the - method in Date and not DateTime, you can't use ActiveSupport::Duration with DateTime.

I think this is a bug in active_support, since it is assuming too much about the implementation of DateTime.  I'll report it as a bug on Rails' Lighthouse.

**Comment by jeremyevans** [comment]
I added a Rails' Lighthouse ticket for this: https://rails.lighthouseapp.com/projects/8994-ruby-on-rails/tickets/6062

I also emailed the rails-core mailing list to alert them to the issue.

**Comment by xn** [comment]
Awesome, thanks. Could your suggestion be run in an initializer within rails?

**Comment by jeremyevans** [comment]
It could.  I think my code will work fine if home_run is installed, but probably needs a guard if it is not installed.  I'm going to work on a real patch today and test it both with and without home_run.

**Comment by xn** [comment]
Oh, and by the way, digging a bit deeper into minus, the method 'since' can fail.

Try
x = DateTime(2001)
x.since(1.minute) # works
x.since(-1.minute) # works
x.since(1.minute.ago) # fails

**Comment by jeremyevans** [comment]
That method fails without home_run too.  DateTime#since takes a number in seconds, not a Time (which is what 1.minute.ago returns).

**Comment by xn** [comment]
Oops, sorry.

**Comment by pivotalcommon** [comment]
We've gone down the rabbit hole a little more.

_deep breath_

The issue with ActiveSupport and home_run is that ActiveSupport assumes that DateTime object inherits its base from Date object. ActiveSupport modifies Date object plus and minus methods to handle duration objects (1.day, 2.hours, etc).

When looking at date.rb in the base Ruby 1.9.2 implementation, DateTime does inherit from Date.

home_run declares the DateTime object and Date objects as two separate entities.

A lot of these issues could be corrected if home_run's DateTime object inherited correctly from Date. My only _gotchya_ for this would that DateTime should not have certain methods defined for it because it should naturally inherit them from the Date object. Please see date.rb in Ruby 1.9.2 for those methods.

These are the default DateTime methods that are actually defined for DateTime, everything else appears to be inherited from Date object.

> require "date"
> DateTime.methods - Date.methods
> => [:now] 
> DateTime.instance_methods - Date.instance_methods
>  => [:hour, :min, :sec, :sec_fraction, :zone, :offset, :new_offset, :minute, :second, :second_fraction]
> DateTime.private_methods - Date.private_methods
>  => [:today] 

etc....

**Comment by jeremyevans** [comment]
Yes, all this is explained in the above comments and the Lighthouse ticket.
