### ISSUE TITLE
adding 1.year results in incorrect new date

### ISSUE THREAD

**Issue by iros** [jeremyevans/home_run#26]
I recently switched to home_run and observed several failures in my rails app test suite. Upon investigating further, here is an example of the sort of behavior I am seeing.

start = DateTime::parse("January 1 1943")

> Fri, 01 Jan 1943 00:00:00 +0000
> start + 1.year
> Tue, 10 Oct 88344 00:00:00 +0000

Naturally, I expected Fri, 01 Jan 1944 00:00:00 +0000.

**Comment by jeremyevans** [comment]
I believe this is the bug in ActiveSupport described here: https://rails.lighthouseapp.com/projects/8994/tickets/6062-activesupport-assumes-too-much-about-how-datedatetime-are-implemented-breaking-some-usage-with-home_run.

The active_support is actually broken on ruby-head as well since tadf committed switch_hitter (replacing the pure ruby date library with a C extension).  I'll add that to the lighthouse ticket.
