### ISSUE TITLE
Serious problems with ActiveSupport 3.1

### ISSUE THREAD

**Issue by titanous** [jeremyevans/home_run#38]
``` ruby
require 'home_run'
require 'active_support/time'

# pegs the CPU forever, leaks memory infinitely in our rails tests
ActiveSupport::TimeZone['Hawaii'].parse('1999-12-31 14:00:00')
```

Tested on AS 3.1.0 and 3.1.1.rc1 with home_run 1.0.4

**Comment by jeremyevans** [comment]
This appears to be a bug in ActiveSupport, at least the fact that pegs the CPU (not seeing any memory leak here, though).  ActiveSupport is using retry in a rescue clause without checking for an infinite loop:

```
module ActiveSupport
  class TimeWithZone
    private
      def get_period_and_ensure_valid_local_time
        # we don't want a Time.local instance enforcing its own DST rules as well,
        # so transfer time values to a utc constructor if necessary
        @time = transfer_time_values_to_utc_constructor(@time) unless @time.utc?
        begin
          @time_zone.period_for_local(@time)
        rescue ::TZInfo::PeriodNotFound
          # time is in the "spring forward" hour gap, so we're moving the time forward one hour and trying again
          @time += 1.hour
          retry
        end
      end
  end
end
```

So for home_run, the problem is that @time_zone.period_for_local(@time) is raising ::TZInfo::PeriodNotFound.  If I had to guess, I'd guess an issue with TZInfo::TimeOrDateTime, but that's not really an educated guess at this point.  I'm not going to have a lot of time to review this issue in the near future, so for resolution you should investigate and see if that is the underlying problem, or just not use home_run.  You could also try using ruby 1.9.3, as it has a rewritten Date class that is almost as fast as home_run.

**Comment by jeremyevans** [comment]
I've confirmed that the root cause of this is an ActiveSupport bug (https://github.com/rails/rails/pull/2797).  You can work around the issue in your code by doing:

```
class DateTime
  alias foo <=>
end

require 'active_support/time'

class DateTime
  alias <=> foo
end
```

Basically, ActiveSupport 3.1 breaks `DateTime#<=>` by assuming that `DateTime#<=>` is implemented by `Date#<=>`, which is not true in home_run.
