### ISSUE TITLE
home_run and Rails 3.1/3.2 fix?

### ISSUE THREAD

**Issue by sr3d** [jeremyevans/home_run#45]
Knowing that Home_run is incompatible with ActiveSupport 3.1, is there a plan to make it compatible with Rails?  I'm using 3.2 at the moment and I had to put the hack as in your comment at https://github.com/jeremyevans/home_run/issues/38#issuecomment-2217466

**Comment by jeremyevans** [comment]
Personally, I feel this is a bug in ActiveSupport, and should be fixed there.  However, since this affects quite a few people and the ActiveSupport maintainers haven't done anything about it in over 6 months, I'll certainly consider working around it.  Can you try the patch at http://pastie.org/3448826 ?

**Comment by sr3d** [comment]
@jeremyevans uhm ... sorry for being a total noob -- how would I apply the patch?  Looks like the patched is to be applied to home_run.

**Comment by jeremyevans** [comment]
git apply in a home_run checkout should work, then use rake gem to build the gem, and gem install to install it.  Since there already exists a patch to fix ActiveSupport (https://github.com/cgriego/rails/commit/c9ea98a75f6e53c4a32ba73a46f94e520072d3c2, which they haven't bothered to apply), I assumed you wanted a patch to home_run to work around the ActiveSupport brokenness.

**Comment by sr3d** [comment]
Thanks.  So for production deployment, how'd you do it?  Fork the gem, apply the patch, push back to the fork on Github, then point bundle's Gemfile to the patched gem repo?

**Comment by jeremyevans** [comment]
That seems reasonable to me if the gem has to be installed via bundler.  I'm assuming you've done local testing of the patch first, right? :)

**Comment by jeremyevans** [comment]
I've released version 1.0.6 with the patch in this ticket.  It's a shame I have to work around bugs in ActiveSupport, but it wouldn't be the first time.
