### ISSUE TITLE
home_run and rails built in date helpers

### ISSUE THREAD

**Issue by jwaldrip** [jeremyevans/home_run#47]
When I have home run enabled... the date helpers such as `Date.today.years_ago(5)` do not work. Is there a way to add these helpers back in?

**Comment by jeremyevans** [comment]
This works fine over here.  If you are having problems, it's probably because you are loading the stdlib date first, then active_support (which adds the extensions to Date), then home_run (which replaces Date). Try switching it so that home_run is loaded first.  One easy to to do this is to use home_run to execute the command (`home_run rails ...`) or using `home_run --install` to install home_run to site-ruby so it gets loaded instead of the stdlib library.

**Comment by jwaldrip** [comment]
Perfect. Just required it before and it works great. Thanks!
