### ISSUE TITLE
Unnecessary in 1.9.3+?

### ISSUE THREAD

**Issue by squarism** [jeremyevans/home_run#48]
I was playing with this gem this week and love the idea.  I found the docs great, the README great and the included benchmarks perfect.  After benching many different ways, I couldn't find out why C Ruby was faster than JRuby.  I couldn't see any speed up when using the home_run gem.

Come to find out though that 1.9.3 has implemented C extensions for Date and DateTime.  After re-reading the speedup table in README now it's clear why there isn't a 1.9.3 column.

Could you add some blurb to this effect in the README?  It might make it more clear to newcomers that this gem might possibly have no effect on performance from 1.9.3+.

Thank you for you contributions to OSS.

**Comment by jeremyevans** [comment]
The 1.9.3 date C extension (development name: switch_hitter) was developed in response to home_run (since home_run itself was not compatible enough to replace the pure-ruby version).

There are differences between how home_run operates and how 1.9.3 date C extension operates (especially for parsing, since home_run uses ragel), and conceivably it would make sense to use home_run even on 1.9.3+ in very specific use cases.  However, I agree in general that we should mention something in the README about this.  I'll work on it right away.
